apiVersion: 1.0.0

previews:
  - name: default
    container:
      image: hferentschik/sample-app-minimal:${{env.commit.sha}}
      ports:
        - value: 80
  - name: debug-context
    container:
      image: hferentschik/sample-app-minimal:${{env.commit.sha}}
      ports:
        - value: 80
